### ISSUE TITLE
Multiple Commits 

### ISSUE THREAD

**Issue by andreas-john-dev** [aws-samples/aws-codecommit-selective-build-trigger#1]
Hey :)
Thanks for your solution. 
I wanna give it a try, but I have a question first.

What happens if I'm doing multiple commits locally and pushing then all of them at once. Is it possible to not only get the latest commit, but all commits of the latest push? 

Best regards

**Comment by praveenflash** [comment]
Hi,

Thanks for posting your question! At this point, only the latest commit's files are taken into account. Will update the solution if I find a solution to get all the files in a push
